### ISSUE TITLE
Erroring out while trying to create cache entry

### ISSUE THREAD

**Issue by bjornharvold** [patrickvankann/spring-cache-gae#26]
Hi,

I see this repo hasn't been used in a while. Would you know why this is happening when using your implementation?

> Can't make API call memcache.Get in a thread that is neither the original request thread nor a thread created by ThreadManager

I am using Spring's @Cacheable annotation

Cheers,
Bjorn

**Comment by patrickvankann** [comment]
Hi,
I haven't looked at this in a long time as recent projects have not featured Spring and Google App Engine. Is there any chance you could send the full stacktrace and a bit more info about your project (Spring version, context in which error occurs) or even better upload a minimal reproducer to a git repo somewhere so I could have a look?
Thanks,
Patrick

**Comment by bjornharvold** [comment]
Hi Patrick,

Thank you so much for getting in touch here as I know it's been a while :-)

I am using Spring's @EnableCaching and would just like a "drop in" cacheManager implementation to be available. I am using Spring's cache abstraction and am only using @Cacheable and @CacheEvict.

The code should've just look like this for JSR 107 and all would be good:
public class JSR107CacheConfig implements JCacheManagerCustomizer {

   ```
 @Override
    public void customize(CacheManager cacheManager) {
        log.info(String.format("Using JCache (JSR 107) implementation by: %s", cacheManager.getClass().getSimpleName()));

        cacheManager.createCache("checklist", new MutableConfiguration<>()
                .setExpiryPolicyFactory(TouchedExpiryPolicy.factoryOf(new Duration(MINUTES, 10)))
                .setStoreByValue(false)
                .setStatisticsEnabled(true));
    }

}
```

Locally, I am using ehCache's JCache JSR 107 implementation without any issues. GAE said they were also JSR 107 compliant but they are not. Their API is an implementation of a non-final version of JSR 107. Unfortunate really as it would've been nice to just see it work. Instead, when the app starts app, it just fails to find any real JSR 107 implementation and starts up without caching enabled.

Then I thought to myself, "Now I have to spend my time writing a cache manager implementation on top of Memcache's lower level API".... but then I came across your codebase and saw that you had beat me to it.

For your implementation, I followed your instructions and just exposed your cache manager through  java config @Bean notation. Everything started up fine but the moment it goes to save, I get the error I mentioned above.

There is some AOT class weaving in place here with @Cacheable so I am wondering if that's the issue. 

Any ideas?

Cheers and appreciated!
Bjorn

**Comment by patrickvankann** [comment]
Hi Bjorn,

Any chance of pasting in a stack trace at least? And let me know what versions of everything (e.g. Spring, the Google App Engine SDK) are in play here. Otherwise, I have no way of knowing what the issue is.

Cheers,
Patrick

**Comment by bjornharvold** [comment]
Hi Patrick,

There was no stacktrace unfortunately. Just that one-liner in GCP logging console.

Here are details:
- Spring Boot 1.5.3
- Spring 4.3.8
- Google App Engine SDK 1.9.53

There's a sample here: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-cache you can use to plugin in your code and another one with the appengine maven plugin already in place here: https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/helloworld-springboot.

Let me know what else I can help you with.

Cheers,
Bjorn

**Comment by patrickvankann** [comment]
Hi Bjorn,

Thanks for those apps - I was able to get a Spring Boot app running and integrate my GAE memcache library with it. The bad news is that I can replicate the error using the @Cacheable annotation. The worse news is that the error occurs even if you use the MemcacheService API directly in Spring Boot. For example, even something as simple as:

   ```
    @Autowired
    private MemcacheService memcacheService;

    @RequestMapping("/test")
    public String test() {
      String message = (String)memcacheService.get("message");
      if (null == message) {
        message = "hello";
        memcacheService.put("message", message);
      }
      return message;
    }
```
Causes exactly the same error. I also tried it without injecting the MemcacheService (creating it in the controller directly using MemcacheServiceFactory). 

So the problem isn't in my library - it just doesn't seem like the MemcacheService API can be used from Spring Boot. It may be that some type of integration between Spring Boot and the ThreadManager is needed so that requests handled by Spring Boot are using threads that are created by the ThreadManager.

https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/ThreadManager 

I had a quick Google and looked at the SpringApplication JavaDoc but could see no obvious way of making Spring use a different ThreadFactory, or indeed if Spring is creating threads in the background. Sorry I can't help more but maybe this will give you a clue as to what to try next. Perhaps using the MemcacheService directly in a plain Servlet?

**Comment by bjornharvold** [comment]
Hi Patrick,

Thank you for that. Creating a bug request now.

**Comment by patrickvankann** [comment]
Let me know what you find out. If further configuration is needed for modern versions of Spring, I will update the docs as well as bump the Spring and App Engine SDK versions in Maven and make a new release.

**Comment by bjornharvold** [comment]
They are telling me to use @CacheResult instead of @Cacheable. You can find the ticket here: https://issuetracker.google.com/issues/38437357. I will give that a try and get back to you.

**Comment by patrickvankann** [comment]
I don't think this is going to work as literally any attempt to access the MemcacheService API results in the error you are seeing. But let me know how you get on.

**Comment by bjornharvold** [comment]
Cheers Patrick!
